version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    networks:
      - springapimysql-net
    environment:
      - spring.datasource.url=jdbc:mariadb://mariadb:3306/basics?allowPublicKeyRetrieval=true      
    depends_on:
       mariadb:
          condition: service_healthy
    volumes:
      - .m2:/root/.m2
      
  mariadb:
    image: mariadb:latest
    restart: always
    ports:
      - 3306:3306
    networks:
      - springapimysql-net  
    environment:
      MARIADB_DATABASE: basics
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: root
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect","--innodb_initialized"]
      interval: 10s
      timeout: 2s
      retries: 10
networks:
  springapimysql-net: